### ISSUE TITLE
driver/spi_master.h

### ISSUE THREAD

**Issue by sandorkrisz** [harbaum/galagino#12]
Please upload the sound driver library.

galagino:12:10: fatal error: driver/i2s.h: No such file or directory
 #include "driver/i2s.h"
          ^~~~~~~~~~~~~~
compilation terminated.
exit status 1

In file included from D:\galagino\galagino-main\galagino\galagino.ino:13:0:
video.h:7:10: fatal error: driver/spi_master.h: No such file or directory
 #include <driver/spi_master.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
driver/spi_master.h: No such file or directory

**Comment by harbaum** [comment]
These files are part of the ESP32 board package. What board do you have selected? And what ESP32 board support do you have installed?
