### ISSUE TITLE
missing tileaddr.h: No such file

### ISSUE THREAD

**Issue by C64fan** [harbaum/galagino#13]
Hi, 
great project, respect.
I cannot find tileaddr.h , where to get this file ?

**Comment by harbaum** [comment]
You generate it together with many other files using the python scripts in  the romconv directory. 

There's a readme that should give you all the details.

**Comment by C64fan** [comment]
My bad,
Ordered hardware and will build this project.
Indeed very detailed manual, very appreciated.

**Comment by harbaum** [comment]
This is still a work in progress and the next will be a laser cut plywood case.

And the instructions will get a major update then to include the mechanical, electrical and programming related tasks in one consistent document.

Do you plan to put everthing into a case?
