### ISSUE TITLE
ST7735 ?!

### ISSUE THREAD

**Issue by gilmod714** [harbaum/galagino#52]
Hello,
is it possible to add support for TFT st7735  (128x160) ?!

I know it is smaller than the recommended display, but that's what I have at the moment ;)

btw .. I was able to compile and upload the sketch fully to ESP32-dev board .. I looked at the config.h file but couldn't figure out if st7735 is supported or not ..

thank you!

**Comment by harbaum** [comment]
The contents won't fit. I am sure you could add that. But I don't see the point if part of the game area will be missing.
